export const components = {
  common: ['/components/button', '/components/icon'],
  layout: [
    '/components/auto-center',
    '/components/divider',
    '/components/grid',
    '/components/safe-area',
    '/components/space',
  ],
  navigation: [
    '/components/capsule-tabs',
    '/components/jumbo-tabs',
    '/components/nav-bar',
    '/components/side-bar',
    '/components/tab-bar',
    '/components/tabs',
  ],
  dataDisplay: [
    '/components/avatar',
    '/components/card',
    '/components/collapse',
    '/components/list',
    '/components/page-indicator',
    '/components/steps',
    '/components/tag',
    '/components/water-mark',
    '/components/footer',
  ],
  dataEntry: [
    '/components/checkbox',
    '/components/input',
    '/components/search-bar',
    '/components/selector',
    '/components/radio',
    '/components/stepper',
    '/components/switch',
  ],
  feedback: [
    '/components/dot-loading',
    '/components/spin-loading',
    '/components/mask',
    '/components/popup',
    '/components/progress-bar',
    '/components/progress-circle',
    '/components/result',
    '/components/skeleton',
    '/components/toast',
  ],
  guidance: ['/components/badge', '/components/notice-bar'],
};
